### ISSUE TITLE
[BACKEND] [WEBHOOK] Set up secure WEBHOOK for stripe payments

### ISSUE THREAD

**Issue by bcho892** [UoaWDCC/uasc-web#131]
**Is your feature request related to a problem? Please describe.**
We want all of our logic related to successful club sign up and booking payments to come from Stripe, and not the client. For this reason we should set up [a webhook](https://docs.stripe.com/webhooks)

Decide on an appropriate name for the webhook.

**Describe the solution you'd like**
This ticket does not involve any business logic, but we do have to follow the docs to make sure randos can't hit this endpoint

also make sure that we acknowledge with `{recieved: true}` in the `200` response

test and verify this with the strip CLI

**BEFORE MERGING**
- [x] Integration test written for services
- [x] Code generation run (*hint*: `yarn workspace server tsoa spec-and-routes`)
- [x] Appropriate mocks created where possible
- [ ] PR Reviewed (For non-trivial changes)
- [ ] Changes tested after rebasing on master or merging in master (*hint*: `git fetch origin master:master`, then `git rebase master` or `git merge master`)
- [ ] All required PR checks passing

```[tasklist]
### Tasks
```

**Comment by jeffplays2005** [comment]
- [ ] Acknowledge webhook with a 200 response
- [ ] Reject with 400 error on any invalid requests

- [ ] Store webhook data upon receive
