### ISSUE TITLE
[BACKEND] Setup endpoint(s) for admin to edit a user's membership status

### ISSUE THREAD

**Issue by bcho892** [UoaWDCC/uasc-web#202]
**Is your feature request related to a problem? Please describe.**
While an admin can create a user using the signup endpoint, they'll need to be able to change the status of a user to a member (in case they paid by bank transfer)

it might be worth to have two endpoints to demote users to guest and have one to promote to member. This should be done using the userservice and authservice. (we have to update their claims as well as their firestore document)

needs to be scoped to an admin and should not work on admin accounts (to prevent accidents)

Note the claims function in `AuthService` should be modified to remove claims as well

**BEFORE MERGING**
- [x] Integration test written for services
- [ ] [Schemas annotated](https://tsoa-community.github.io/docs/annotations.html) if adding new models
- [x] Code generation run (*hint*: `yarn workspace server tsoa spec-and-routes`)
- [ ] Appropriate mocks created where possible
- [ ] PR Reviewed (For non-trivial changes)
- [ ] Changes tested after rebasing on master or merging in master (*hint*: `git fetch origin master:master`, then `git rebase master` or `git merge master`)
- [ ] All required PR checks passing

```[tasklist]
### Tasks
```

**Comment by jeffplays2005** [comment]
- [ ] Scope to admin
- [ ] Not work on admin accounts
- [ ] Claims function in AuthService modified to remove claims as well
